version: '3.4'

services:
  onionarchitecture.web:
    image: ${DOCKER_REGISTRY-}onionarchitectureweb
    container_name: onionarchitecture_web
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - 5000:80      
    depends_on:
      - onionarchitecture.db

  onionarchitecture.db:
    image: mcr.microsoft.com/mssql/server    
    container_name: onionarchitecture_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=@Password01
    volumes:
      - ./db:/var/lib/mssql/data
    ports:
      - 1433:1433
