version: '3.4'
services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server    
        container_name: onionarchitecture_db
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_PID=Developer
            - MSSQL_SA_PASSWORD=@Password123
        volumes:
            - ./db:/var/lib/mssql/data
        ports:
            - 1433:1433      
    mssqltools:
        image: mcr.microsoft.com/mssql-tools        
        volumes:
            - ./db-create.sql:/tmp/db-create.sql                  
        command: /bin/bash -c "sleep 10 && /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P @Password123 -d master -i /tmp/db-create.sql"
        depends_on:
            - sqlserver
    onionarchitecture:
        image: ${DOCKER_REGISTRY-}onionarchitecture
        container_name: onionarchitecture_web
        build:
            context: .
            dockerfile: Web/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - 5000:80      
        depends_on:
            - mssqltools

  


